version: '3'
services:
  web_server:
    container_name: hugo_server
    image: klakegg/hugo:0.83.1
    command:
     - server
    volumes:
      - ".:/src"
    ports:
      - "1313:1313"
  netlifly_cms:
    container_name: netlifly_cms
    build: .
    volumes:
      - ".:/src"
    ports:
      - "80:8081"
