version: '3'
services:
  web_server:
    container_name: hugo_server
    image: klakegg/hugo:0.83.1
    command:
     - server --bind=0.0.0.0 --port 8080
    volumes:
      - ".:/src"
    ports:
      - "8080:8080"
  netlifly_cms:
    container_name: netlifly_cms
    build: .
    volumes:
      - ".:/src"
    ports:
      - "80:8081"
