#backend:
#  name: github
#  repo: AratioD/simplejam1

backend:
  name: git-gateway
  branch: main
  
media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "page"
    label: "Page"
    folder: "content/"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "author", widget: "select", options: ["AratioD"]}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Content", name: "body", widget: "markdown"}

  - name: "premium"
    label: "Premium Page"
    folder: "content/premium"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "author", widget: "select", options: ["AratioD", "pekka"]}
      - {label: "Date", name: "date", widget: "datetime"}
